name: Auto Tag
on:
  push:
    branches: [main]
    paths: ['package.json']

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get version from package.json
        id: version
        run: echo "version=v$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
      - name: Check if tag exists
        id: tag_exists
        run: |
          git fetch --tags
          if git rev-parse ${{ steps.version.outputs.version }} >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Tag ${{ steps.version.outputs.version }} already exists, skipping creation"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Tag ${{ steps.version.outputs.version }} does not exist, will create"
          fi
      
      - name: Create and push tag
        if: steps.tag_exists.outputs.exists == 'false'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}
      
      - name: Tag already exists
        if: steps.tag_exists.outputs.exists == 'true'
        run: |
          echo "✅ Tag ${{ steps.version.outputs.version }} already exists - no action needed"
          echo "This is expected behavior when the version hasn't changed"
      
