name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install system dependencies for Puppeteer
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libnss3-dev \
          libatk-bridge2.0-dev \
          libdrm-dev \
          libgtk-3-dev \
          libgbm-dev
    
    - name: Install dependencies
      run: npm install
    
    - name: Start server in background
      run: |
        npm run dev &
        echo $! > server.pid
      
    - name: Wait for server to start
      run: |
        echo "🔄 Waiting for server to start on port 8777..."
        timeout 30 bash -c 'until nc -z localhost 8777; do sleep 1; done'
        echo "✅ Server is ready!"
    
    - name: Run tests
      run: make test
      env:
        CI: true
      
    - name: Upload screenshots on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-failure-screenshots
        path: screenshots/
        retention-days: 7
        if-no-files-found: ignore
      
    - name: Stop server
      run: |
        if [ -f server.pid ]; then
          kill $(cat server.pid) || true
          rm server.pid
        fi
      if: always()